VOCATION_FIRE  = 1
VOCATION_WATER = 2
VOCATION_AIR = 3
VOCATION_EARTH  = 4

SpellInfo = {
	-- configuração das spells
	
	-- spells de fire ---------------------------
	["fire wave"] = {
		spellId = 101,
		words = 'fire wave',
		description = 'conjures a cone of fire in front of the player.',
		icon = '/images/game/spelltree/fire/fire_wave',
	},
	["fire punch"] = {
		spellId = 102,
		words = 'fire punch',
		description = 'punch the enemy repeatedly dealing constant damage.',
		icon = '/images/game/spelltree/fire/fire_punch',
	},
	["fire flash"] = {
		spellId = 103,
		words = 'fire flash',
		description = 'paralyzes a single target.',
		icon = '/images/game/spelltree/fire/fire_flash',
	},
	["fire flames"] = {
		spellId = 104,
		words = 'fire flames',
		description = 'conjures a large area of flames around the player dealing constant damage.',
		icon = '/images/game/spelltree/fire/fire_flames',
	},
	["fire bite"] = {
		spellId = 105,
		words = 'fire bite',
		description = 'does damage in a area around the target.',
		icon = '/images/game/spelltree/fire/fire_bite',
	},
	["fire cannon"] = {
		spellId = 106,
		words = 'fire cannon',
		description = 'pushes enemies on the side of the player.',
		icon = '/images/game/spelltree/fire/fire_cannon',
	},
	["fire beam"] = {
		spellId = 107,
		words = 'fire beam',
		description = 'charges a little bit and does damage in a straight line.',
		icon = '/images/game/spelltree/fire/fire_beam',
	},
	["fire ball"] = {
		spellId = 108,
		words = 'fire ball',
		description = 'throws a fire ball in a single target dealing aoe damage.',
		icon = '/images/game/spelltree/fire/fire_ball',
	},
	["fire wrath"] = {
		spellId = 109,
		words = 'fire wrath',
		description = 'imprison the target for a short period of time.',
		icon = '/images/game/spelltree/fire/fire_wrath',
	},
	["fire jump"] = {
		spellId = 110,
		words = 'fire jump',
		description = 'raises the player for short period of time allowing him to walk in your own.',
		icon = '/images/game/spelltree/fire/fire_jump',
	},
	["fire star"] = {
		spellId = 111,
		words = 'fire star',
		description = 'deals constant aoe damage around the player for a short period of time.',
		icon = '/images/game/spelltree/fire/fire_star',
	},
	["fire doublekick"] = {
		spellId = 112,
		words = 'fire doublekick',
		description = 'shoots a strong fire kick at the target.',
		icon = '/images/game/spelltree/fire/fire_doublekick',
	},
	["fire breath"] = {
		spellId = 113,
		words = 'fire breath',
		description = 'releases the player from any negative movement condition he has.',
		icon = '/images/game/spelltree/fire/fire_breath',
	},
	["fire storm"] = {
		spellId = 114,
		words = 'fire storm',
		description = 'creates a fire storm in a big area dealing aoe damage.',
		icon = '/images/game/spelltree/fire/fire_storm',
	},
	["fire cry"] = {
		spellId = 115,
		words = 'fire cry',
		description = 'deals single target damage in cross-shaped.',
		icon = '/images/game/spelltree/fire/fire_cry',
	},
	["fire bomb"] = {
		spellId = 116,
		words = 'fire bomb',
		description = 'fires a strong fire bomb at the target, leaving it with the effect of "miss".',
		icon = '/images/game/spelltree/fire/fire_bomb',
	},
	["fire impulse"] = {
		spellId = 117,
		words = 'fire impulse',
		description = 'propels the player for a few seconds in the direction he is facing.',
		icon = '/images/game/spelltree/fire/fire_impulse',
	},
	["fire snakes"] = {
		spellId = 118,
		words = 'fire snakes',
		description = 'deals constant damage in enemies around the player.',
		icon = '/images/game/spelltree/fire/fire_snakes',
	},
	["fire skyfall"] = {
		spellId = 119,
		words = 'fire skyfall',
		description = 'fires fireballs into the sky and moments after firing, the balls come back and cause damage. they can also knock down players in the "jump" ability',
		icon = '/images/game/spelltree/fire/fire_skyfall',
	},
	["fire clock"] = {
		spellId = 120,
		words = 'fire clock',
		description = 'creates a whirlwind of fire around the player, trapping nearby targets making them spin and preventing them from using folds for a few seconds.',
		icon = '/images/game/spelltree/fire/fire_clock',
	},
	["fire meteor"] = {
		spellId = 121,
		words = 'fire meteor',
		description = 'a heavy meteor shower is initiated causing major damage to targets within a perimeter of up to 5 sqms away from the player.',
		icon = '/images/game/spelltree/fire/fire_meteor',
	},
	["fire yell"] = {
		spellId = 122,
		words = 'fire yell',
		description = 'requires a target the spell and causes aoe damage on the target.',
		icon = '/images/game/spelltree/fire/fire_yell',
	},
	["fire explosion"] = {
		spellId = 123,
		words = 'fire explosion',
		description = 'a large explosion occurs that pushes nearby targets within a perimeter of up to 5 sqms away.',
		icon = '/images/game/spelltree/fire/fire_explosion',
	},
	["fire striker"] = {
		spellId = 124,
		words = 'fire striker',
		description = 'an aura of fire is created around the player for a few seconds, causing major damage to targets that are within a perimeter of up to 2 sqms away.',
		icon = '/images/game/spelltree/fire/fire_striker',
	},
	["fire spark"] = {
		spellId = 125,
		words = 'fire spark',
		description = 'deals aoe damage on the target.',
		icon = '/images/game/spelltree/fire/fire_spark',
	},
	["fire dragon"] = {
		spellId = 126,
		words = 'fire dragon',
		description = 'summons a dragon to help you in battle.',
		icon = '/images/game/spelltree/fire/fire_dragon',
	},
	["fire burnsteps"] = {
		spellId = 127,
		words = 'fire burnsteps',
		description = 'your feet starts to get on fire, as you walk you will do damage around you.',
		icon = '/images/game/spelltree/fire/fire_burnsteps',
	},
	["fire overheat"] = {
		spellId = 128,
		words = 'fire overheat',
		description = 'deals aoe damage on the target.',
		icon = '/images/game/spelltree/fire/fire_overheat',
	},
	["fire smoke"] = {
		spellId = 129,
		words = 'fire smoke',
		description = 'creates a big smoke paralyzing enemies inside of it.',
		icon = '/images/game/spelltree/fire/fire_smoke',
	},
	["fire rage"] = {
		spellId = 130,
		words = 'fire rage',
		description = 'the player will release several waves of blue fire causing huge damage to targets.',
		icon = '/images/game/spelltree/fire/fire_rage',
	},
	["fire hellcurse"] = {
		spellId = 131,
		words = 'fire hellcurse',
		description = 'curses the target dealing damage based on his movement.',
		icon = '/images/game/spelltree/fire/fire_hellcurse',
	},
	["fire fog"] = {
		spellId = 132,
		words = 'fire fog',
		description = 'paralyzes targets in a big area and has a chance to give the effect "miss". ',
		icon = '/images/game/spelltree/fire/fire_fog',
	},

	
	-- spells de water ---------------------------
	["water heal"] = {
		spellId = 201,
		words = 'water heal',
		description = 'heals a large amount of targets health',
		icon = '/images/game/spelltree/water/water_heal',
	},
	["water explosion"] = {
		spellId = 202,
		words = 'water explosion',
		description = 'fires a water bubble at the target causing a water explosion.',
		icon = '/images/game/spelltree/water/water_explosion',
	},
	["water cannon"] = {
		spellId = 203,
		words = 'water cannon',
		description = 'fires a sound of water in all directions, pushing targets.',
		icon = '/images/game/spelltree/water/water_cannon',
	},
	["water manaheal"] = {
		spellId = 204,
		words = 'water manaheal',
		description = 'heals a large amount of targets mana.',
		icon = '/images/game/spelltree/water/water_manaheal',
	},
	["water icewave"] = {
		spellId = 205,
		words = 'water icewave',
		description = 'creates an ice wave dealing damage.',
		icon = '/images/game/spelltree/water/water_icewave',
	},
	["water icebolt"] = {
		spellId = 206,
		words = 'water icebolt',
		description = 'fires a strong beam of ice at the target and leaves it frozen for a few moments, preventing the target from walking and using folds.',
		icon = '/images/game/spelltree/water/water_icebolt',
	},
	["water purify"] = {
		spellId = 207,
		words = 'water purify',
		description = 'purifies the target from any negative condition he has.',
		icon = '/images/game/spelltree/water/water_purify',
	},
	["water wave"] = {
		spellId = 208,
		words = 'water wave',
		description = 'deals damage in front of you.',
		icon = '/images/game/spelltree/water/water_wave',
	},
	["water icespikes"] = {
		spellId = 209,
		words = 'water icespikes',
		description = 'fires fragments of ice into the sky and moments after firing, the fragments return and cause a wave of ice horizontally in the direction you are facing.',
		icon = '/images/game/spelltree/water/water_icespikes',
	},
	["water jump"] = {
		spellId = 210,
		words = 'water jump',
		description = 'raises the player for short period of time allowing him to walk in your own.',
		icon = '/images/game/spelltree/water/water_jump',
	},
	["water masshealing"] = {
		spellId = 211,
		words = 'water masshealing',
		description = 'heals a certain amount of health for the player and nearby allies.',
		icon = '/images/game/spelltree/water/water_masshealing',
	},
	["water clock"] = {
		spellId = 212,
		words = 'water clock',
		description = 'controls a large amount of water by creating a whirlwind around the player, causing nearby targets to take a large amount of damage.',
		icon = '/images/game/spelltree/water/water_clock',
	},
	["water jet"] = {
		spellId = 213,
		words = 'water jet',
		description = 'slows the target.',
		icon = '/images/game/spelltree/water/water_jet',
	},
	["water flow"] = {
		spellId = 214,
		words = 'water flow',
		description = 'creates an aura of healing around you and, at the same time, releases water bubbles that hit nearby enemies.',
		icon = '/images/game/spelltree/water/water_flow',
	},
	["water vortex"] = {
		spellId = 215,
		words = 'water vortex',
		description = 'deals aoe damage.',
		icon = '/images/game/spelltree/water/water_vortex',
	},
	["water pump"] = {
		spellId = 216,
		words = 'water pump',
		description = 'deals damage and slows the targets in a cone-shaped area.',
		icon = '/images/game/spelltree/water/water_pump',
	},
	["water surf"] = {
		spellId = 217,
		words = 'water surf',
		description = 'propels the player for a few seconds in the direction he is facing.',
		icon = '/images/game/spelltree/water/water_surf',
	},
	["water masspurify"] = {
		spellId = 218,
		words = 'water masspurify',
		description = 'purifies allies in a area around the player.',
		icon = '/images/game/spelltree/water/water_masspurify',
	},
	["water shards"] = {
		spellId = 219,
		words = 'water shards',
		description = 'it channels ice around the player, hitting nearby targets.',
		icon = '/images/game/spelltree/water/water_shards',
	},
	["water icegolem"] = {
		spellId = 220,
		words = 'water icegolem',
		description = 'creates an ice golem with plenty of life, but without regeneration, dealing a little bit of damage.',
		icon = '/images/game/spelltree/water/water_icegolem',
	},
	["water spirit"] = {
		spellId = 221,
		words = 'water spirit',
		description = 'creates an water spirit with plenty of life, but with regeneration.',
		icon = '/images/game/spelltree/water/water_spirit',
	},
	["water bubbles"] = {
		spellId = 222,
		words = 'water bubbles',
		description = 'shoot 5 bubbles of water at the target. the last bubble will have a "drowned" effect on the target, causing 5 consecutive damages.',
		icon = '/images/game/spelltree/water/water_bubbles',
	},
	["water icebeam"] = {
		spellId = 223,
		words = 'water icebeam',
		description = 'deals damage in a straight line, and freezes hit targets.',
		icon = '/images/game/spelltree/water/water_icebeam',
	},
	["water manaflow"] = {
		spellId = 224,
		words = 'water manaflow',
		description = 'creates an aura of mana healing around the player, healing nearby allies.',
		icon = '/images/game/spelltree/water/water_manaflow',
	},
	["water geiser"] = {
		spellId = 225,
		words = 'water geiser',
		description = 'deals aoe damage.',
		icon = '/images/game/spelltree/water/water_geiser',
	},
	["water tsunami"] = {
		spellId = 226,
		words = 'water tsunami',
		description = 'fires a huge wave of water horizontally in the direction you are facing, pushing the targets.',
		icon = '/images/game/spelltree/water/water_tsunami',
	},
	["water protect"] = {
		spellId = 227,
		words = 'water protect',
		description = 'creates a wall of water around the player and leaves him immune to any damage for a few seconds.',
		icon = '/images/game/spelltree/water/water_protect',
	},
	["water sharks"] = {
		spellId = 228,
		words = 'water sharks',
		description = 'deals damage in a front area.',
		icon = '/images/game/spelltree/water/water_icewind',
	},
	["water dragon"] = {
		spellId = 229,
		words = 'water dragon',
		description = 'creates a large water dragon, which shoots fragments of water at nearby targets. it is only possible to use this fold close to a large amount of water.',
		icon = '/images/game/spelltree/water/water_dragon',
	},
	["water healaura"] = {
		spellId = 230,
		words = 'water healaura',
		description = 'creates an aura of healing and mana healing around the player, healing nearby allies.',
		icon = '/images/game/spelltree/water/water_healaura',
	},
	["water strikeaura"] = {
		spellId = 231,
		words = 'water strikeaura',
		description = 'deals aoe damage around the player.',
		icon = '/images/game/spelltree/water/water_strikeaura',
	},
	["water freezingaura"] = {
		spellId = 232,
		words = 'water freezingaura',
		description = 'has a chance of freezing targets in a big area.',
		icon = '/images/game/spelltree/water/water_freezingaura',
	},


	-- spells de air ---------------------------
	["air burst"] = {
		spellId = 301,
		words = 'air burst',
		description = 'pushes targets around you to a perimeter outside the fold area.',
		icon = '/images/game/spelltree/air/air_burst',
	},
	["air ball"] = {
		spellId = 302,
		words = 'air ball',
		description = 'shoots an air ball at the target.',
		icon = '/images/game/spelltree/air/air_ball',
	},
	["air fist"] = {
		spellId = 303,
		words = 'air fist',
		description = 'deals damage and pushes the target.',
		icon = '/images/game/spelltree/air/air_fist',
	},
	["air run"] = {
		spellId = 304,
		words = 'air run',
		description = 'increases the players speed for a few seconds.',
		icon = '/images/game/spelltree/air/air_run',
	},
	["air breath"] = {
		spellId = 305,
		words = 'air breath',
		description = 'deals aoe damage.',
		icon = '/images/game/spelltree/air/air_breath',
	},
	["air gust"] = {
		spellId = 306,
		words = 'air gust',
		description = 'it causes a strong wave of air horizontally in the direction you are facing, pushing the targets in front of you.',
		icon = '/images/game/spelltree/air/air_gust',
	},
	["air massrun"] = {
		spellId = 307,
		words = 'air massrun',
		description = 'gives speed for nearby allies.',
		icon = '/images/game/spelltree/air/air_massrun',
	},
	["air gale"] = {
		spellId = 308,
		words = 'air gale',
		description = 'causes a strong tornado wave horizontally in the direction you are facing, pushing targets up to 3 sqms vertically, depending on the position each target is in.',
		icon = '/images/game/spelltree/air/air_gale',
	},
	["air claw"] = {
		spellId = 309,
		words = 'air claw',
		description = 'pulls the target 1 sqm closer.',
		icon = '/images/game/spelltree/air/air_claw',
	},
	["air jump"] = {
		spellId = 310,
		words = 'air jump',
		description = 'raises the player for short period of time allowing him to walk in your own.',
		icon = '/images/game/spelltree/air/air_jump',
	},
	["air haze"] = {
		spellId = 311,
		words = 'air haze',
		description = 'paralyzes targets a in area around the player.',
		icon = '/images/game/spelltree/air/air_haze',
	},
	["air windcall"] = {
		spellId = 312,
		words = 'air windcall',
		description = 'deals aoe damage, needing a target.',
		icon = '/images/game/spelltree/air/air_windcall',
	},
	["air fan"] = {
		spellId = 313,
		words = 'air fan',
		description = 'it causes a strong wave of air horizontally in the direction you are facing, pushing horizontally from side to side.',
		icon = '/images/game/spelltree/air/air_fan',
	},
	["air voice"] = {
		spellId = 314,
		words = 'air voice',
		description = 'removes the effect "miss".',
		icon = '/images/game/spelltree/air/air_voice',
	},
	["air bomb"] = {
		spellId = 315,
		words = 'air bomb',
		description = 'after charging for a few seconds, it fires a strong air wave that chases the target and explodes upon reaching it.',
		icon = '/images/game/spelltree/air/air_bomb',
	},
	["air trap"] = {
		spellId = 316,
		words = 'air trap',
		description = 'creates an air trap in the sqm in front of the direction you are facing. if a target steps into the trap, it will be trapped for a few seconds.',
		icon = '/images/game/spelltree/air/air_trap',
	},
	["air boost"] = {
		spellId = 317,
		words = 'air boost',
		description = 'propels the player for a few seconds in the direction he is facing..',
		icon = '/images/game/spelltree/air/air_boost',
	},
	["air mirror"] = {
		spellId = 318,
		words = 'air mirror',
		description = 'gives a mirror to an allie, making him reflect a percent of the damage.',
		icon = '/images/game/spelltree/air/air_mirror',
	},
	["air breeze"] = {
		spellId = 319,
		words = 'air breeze',
		description = 'deals aoe damage in a cone-shaped area.',
		icon = '/images/game/spelltree/air/air_breeze',
	},
	["air suffocation"] = {
		spellId = 320,
		words = 'air suffocation',
		description = 'after channeling the target for a few seconds, the target gets the "suffocating" effect for a few moments, preventing the target from walking and using folds.',
		icon = '/images/game/spelltree/air/air_suffocation',
	},
	["air barrier"] = {
		spellId = 321,
		words = 'air barrier',
		description = 'creates an air ball around the player for a few seconds, reducing much of the damage taken and causing some damage to nearby targets.',
		icon = '/images/game/spelltree/air/air_barrier',
	},
	["air windblast"] = {
		spellId = 322,
		words = 'air windblast',
		description = 'creates a line of tornadoes that cause damage and slow time.',
		icon = '/images/game/spelltree/air/air_windblast',
	},
	["air stormcall"] = {
		spellId = 323,
		words = 'air stormcall',
		description = 'a strong advantage of 4 centers is created around the player by making nearby targets sucked and pushed from center to center for a few seconds.',
		icon = '/images/game/spelltree/air/air_stormcall',
	},
	["air sense"] = {
		spellId = 324,
		words = 'air sense',
		description = 'boosts the dodge of the player in a small percent for a short period of time.',
		icon = '/images/game/spelltree/air/air_sense',
	},
	["air cyclones"] = {
		spellId = 325,
		words = 'air cyclones',
		description = 'creates a storm in an area, dealing damage, staying there for 6 seconds.',
		icon = '/images/game/spelltree/air/air_cyclones',
	},
	["air doom"] = {
		spellId = 326,
		words = 'air doom',
		description = 'fires several balls of air at random at targets that are up to 6 sqms apart. whenever a target is hit, it is pushed.',
		icon = '/images/game/spelltree/air/air_doom',
	},
	["air masssense"] = {
		spellId = 327,
		words = 'air masssense',
		description = 'boosts the dodge of your allies around you. it doesnt includes you.',
		icon = '/images/game/spelltree/air/air_masssense',
	},
	["air chains"] = {
		spellId = 328,
		words = 'air chains',
		description = 'deals aoe damage.',
		icon = '/images/game/spelltree/air/air_chains',
	},
	["air windstorm"] = {
		spellId = 329,
		words = 'air windstorm',
		description = 'master around targets that are up to 4 sqms away with a storm, controlling everyone for a few seconds in the direction you are facing.',
		icon = '/images/game/spelltree/air/air_windstorm',
	},
	["air vortex"] = {
		spellId = 330,
		words = 'air vortex',
		description = 'creates an air field for a few seconds that ejects enemies up to 2 sqms away, causing slight damage to the enemy that is expelled or that tries to enter..',
		icon = '/images/game/spelltree/air/air_vortex',
	},
	["air torment"] = {
		spellId = 331,
		words = 'air torment',
		description = 'curses the target dealing damage based on his movement.',
		icon = '/images/game/spelltree/air/air_torment',
	},
	["air stormprison"] = {
		spellId = 332,
		words = 'air stormprison',
		description = 'ar.',
		icon = '/images/game/spelltree/air/air_stormprison',
	},

	
	-- spells de earth ---------------------------
	["earth crush"] = {
		spellId = 401,
		words = 'earth crush',
		description = 'causes a mini-earthquake around you.',
		icon = '/images/game/spelltree/earth/earth_crush',
	},
	["earth rock"] = {
		spellId = 402,
		words = 'earth rock',
		description = 'fires a large stone at the target causing heavy damage and slows for a few moments.',
		icon = '/images/game/spelltree/earth/earth_rock',
	},
	["earth petrify"] = {
		spellId = 403,
		words = 'earth petrify',
		description = 'petrifies the target for a short time.',
		icon = '/images/game/spelltree/earth/earth_petrify',
	},
	["earth challenge"] = {
		spellId = 404,
		words = 'earth challenge',
		description = 'taunts the closest monsters.',
		icon = '/images/game/spelltree/earth/earth_challenge',
	},
	["earth fury"] = {
		spellId = 405,
		words = 'earth fury',
		description = 'dashes pushing the foes back.',
		icon = '/images/game/spelltree/earth/earth_fury',
	},
	["earth pull"] = {
		spellId = 406,
		words = 'earth pull',
		description = 'shoot a large stone at the target by pulling it 2 sqms closer to you.',
		icon = '/images/game/spelltree/earth/earth_pull',
	},
	["earth drain"] = {
		spellId = 407,
		words = 'earth drain',
		description = 'an aura of dust is created around the player for a few seconds, sucking the lives of nearby targets..',
		icon = '/images/game/spelltree/earth/earth_drain',
	},
	["earth collapse"] = {
		spellId = 408,
		words = 'earth collapse',
		description = 'fires stones into the sky and the instant after firing, the stones return and cause a small tremor around them. they can also knock down players in the "jump" ability',
		icon = '/images/game/spelltree/earth/earth_collapse',
	},
	["earth growth"] = {
		spellId = 409,
		words = 'earth growth',
		description = 'creates a wave of stones horizontally in the direction the player is facing, pushing the targets in front of him.',
		icon = '/images/game/spelltree/earth/earth_growth',
	},
	["earth jump"] = {
		spellId = 410,
		words = 'earth jump',
		description = 'raises the player for short period of time allowing him to walk in your own.',
		icon = '/images/game/spelltree/earth/earth_jump',
	},
	["earth shake"] = {
		spellId = 411,
		words = 'earth shake',
		description = 'pushes targets who are standing next to you, 1 sqm.',
		icon = '/images/game/spelltree/earth/earth_shake',
	},
	["earth throw"] = {
		spellId = 412,
		words = 'earth throw',
		description = 'deals damage in front of you.',
		icon = '/images/game/spelltree/earth/earth_throw',
	},
	["earth roots"] = {
		spellId = 413,
		words = 'earth roots',
		description = 'petrifies enemies that are standing next to you.',
		icon = '/images/game/spelltree/earth/earth_roots',
	},
	["earth masschallenge"] = {
		spellId = 414,
		words = 'earth masschallenge',
		description = 'Taunts all creatures in some area around the player.',
		icon = '/images/game/spelltree/earth/earth_challenge',
	},
	["earth smash"] = {
		spellId = 415,
		words = 'earth smash',
		description = 'shoot 3 large stones at the sky and the instant after shooting, the stones return and cause three major damage to the target.',
		icon = '/images/game/spelltree/earth/earth_smash',
	},
	["earth wall"] = {
		spellId = 416,
		words = 'earth wall',
		description = 'creates a wall in front of the player, that stands there for a short period of time.',
		icon = '/images/game/spelltree/earth/earth_wall',
	},
	["earth track"] = {
		spellId = 417,
		words = 'earth track',
		description = 'propels the player for a few seconds in the direction he is facing..',
		icon = '/images/game/spelltree/earth/earth_track',
	},
	["earth guardian"] = {
		spellId = 418,
		words = 'earth guardian',
		description = 'summons a earth guardian to help the player in the battle.',
		icon = '/images/game/spelltree/earth/earth_guardian',
	},
	["earth stomp"] = {
		spellId = 419,
		words = 'earth stomp',
		description = 'deals aoe damage.',
		icon = '/images/game/spelltree/earth/earth_stomp',
	},
	["earth tunnel"] = {
		spellId = 420,
		words = 'earth tunnel',
		description = 'after choosing a target and channeling for a few seconds, if the target does not escape, there will be a change of position.',
		icon = '/images/game/spelltree/earth/earth_tunnel',
	},
	["earth ingrain"] = {
		spellId = 421,
		words = 'earth ingrain',
		description = 'an aura of dust is created around the player, healing and reducing damage for a few seconds.',
		icon = '/images/game/spelltree/earth/earth_ingrain',
	},
	["earth slide"] = {
		spellId = 422,
		words = 'earth slide',
		description = 'shoot 3 large stones at the sky and the instant after shooting, the stones return and does aoe damage.',
		icon = '/images/game/spelltree/earth/earth_slide',
	},
	["earth flow"] = {
		spellId = 423,
		words = 'earth flow',
		description = 'paralyze enemies in an area around the folder..',
		icon = '/images/game/spelltree/earth/earth_flow',
	},
	["earth defense"] = {
		spellId = 424,
		words = 'earth defense',
		description = 'increases the defense of an ally. it is not possible to use on yourself.',
		icon = '/images/game/spelltree/earth/earth_defense',
	},
	["earth recoil"] = {
		spellId = 425,
		words = 'earth recoil',
		description = 'reflects damage received from other sources.',
		icon = '/images/game/spelltree/earth/earth_recoil',
	},
	["earth cataclysm"] = {
		spellId = 426,
		words = 'earth cataclysm',
		description = 'it chases the target at a rapid speed created by earth waves, hitting it creates a ground block around it that holds it.',
		icon = '/images/game/spelltree/earth/earth_cataclysm',
	},
	["earth aura"] = {
		spellId = 427,
		words = 'earth aura',
		description = 'a sand gust is created with 4 stone centers in a perimeter of up to 2 sqms away from the player.',
		icon = '/images/game/spelltree/earth/earth_aura',
	},
	["earth palm"] = {
		spellId = 428,
		words = 'earth palm',
		description = 'a large one hit around the character causing area damage.',
		icon = '/images/game/spelltree/earth/earth_palm',
	},
	["earth arena"] = {
		spellId = 429,
		words = 'earth arena',
		description = 'creates a large 2-story stone arena within a perimeter of up to 5 sqms away from the player, preventing targets from escaping or entering for a few seconds.',
		icon = '/images/game/spelltree/earth/earth_arena',
	},
	["earth armor"] = {
		spellId = 430,
		words = 'earth armor',
		description = 'creates an earth armor that leaves you immune for up to 10 seconds, but prevents you from taking action.',
		icon = '/images/game/spelltree/earth/earth_armor',
	},
	["earth quake"] = {
		spellId = 431,
		words = 'earth quake',
		description = 'a strong earthquake is initiated causing major damage and slowdowns on targets that are within a perimeter of up to 7 sqms away from the player.',
		icon = '/images/game/spelltree/earth/earth_quake',
	},
	["earth revenge"] = {
		spellId = 432,
		words = 'earth revenge',
		description = 'petrifies any enemies for a while around you.',
		icon = '/images/game/spelltree/earth/earth_revenge',
	},


}

WeaponInfo = {
	-- configuração das spells da arma
	["earth lightaxe"] = {
		spellId = 433,
		words = 'earth lightaxe',
		description = 'Deals a light attack.',
		icon = '/images/game/spelltree/axe',
	},
	["earth heavyaxe"] = {
		spellId = 434,
		words = 'earth heavyaxe',
		description = 'Deals a heavy attack.',
		icon = '/images/game/spelltree/axe',
	},
	["earth lightbow"] = {
		spellId = 435,
		words = 'earth lightbow',
		description = 'Deals a light attack.',
		icon = '/images/game/spelltree/flecha',
	},
	["earth heavybow"] = {
		spellId = 436,
		words = 'earth heavybow',
		description = 'Deals a heavy attack.',
		icon = '/images/game/spelltree/flechas',
	},
	["earth lightclub"] = {
		spellId = 437,
		words = 'earth lightclub',
		description = 'Deals a light attack.',
		icon = '/images/game/spelltree/club',
	},
	["earth heavyclub"] = {
		spellId = 438,
		words = 'earth heavyclub',
		description = 'Deals a heavy attack.',
		icon = '/images/game/spelltree/clubs',
	},
	["earth shieldbash"] = {
		spellId = 439,
		words = 'earth shieldbash',
		description = 'Deals a heavy attack.',
		icon = '/images/game/spelltree/spell_03',
	},
	["earth lightsword"] = {
		spellId = 440,
		words = 'earth lightsword',
		description = 'Deals a light attack.',
		icon = '/images/game/spelltree/sword',
	},
	["earth heavysword"] = {
		spellId = 441,
		words = 'earth heavysword',
		description = 'Deals a heavy attack..',
		icon = '/images/game/spelltree/swords',
	},
	["air lightaxe"] = {
		spellId = 333,
		words = 'air lightaxe',
		description = 'Deals a light attack.',
		icon = '/images/game/spelltree/axe',
	},
	["air heavyaxe"] = {
		spellId = 334,
		words = 'air heavyaxe',
		description = 'Deals a heavy attack.',
		icon = '/images/game/spelltree/axes',
	},
	["air lightbow"] = {
		spellId = 335,
		words = 'air lightbow',
		description = 'Deals a light attack.',
		icon = '/images/game/spelltree/flecha',
	},
	["air heavybow"] = {
		spellId = 336,
		words = 'air heavybow',
		description = 'Deals a heavy attack.',
		icon = '/images/game/spelltree/flechas',
	},
	["air lightclub"] = {
		spellId = 337,
		words = 'air lightclub',
		description = 'Deals a light attack..',
		icon = '/images/game/spelltree/club',
	},
	["air heavyclub"] = {
		spellId = 338,
		words = 'air heavyclub',
		description = 'Deals a heavy attack.',
		icon = '/images/game/spelltree/clubs',
	},
	["air shieldbash"] = {
		spellId = 339,
		words = 'air shieldbash',
		description = 'Deals a heavy attack.',
		icon = '/images/game/spelltree/spell_03',
	},
	["air lightsword"] = {
		spellId = 340,
		words = 'air lightsword',
		description = 'Deals a light attack.',
		icon = '/images/game/spelltree/sword',
	},
	["air heavysword"] = {
		spellId = 341,
		words = 'air heavysword',
		description = 'Deals a heavy attack.',
		icon = '/images/game/spelltree/swords',
	},
	["water lightaxe"] = {
		spellId = 233,
		words = 'water lightaxe',
		description = 'Deals a light attack.',
		icon = '/images/game/spelltree/water/axe',
	},
	["water heavyaxe"] = {
		spellId = 234,
		words = 'water heavyaxe',
		description = 'Deals a heavy attack.',
		icon = '/images/game/spelltree/axes',
	},
	["water lightbow"] = {
		spellId = 235,
		words = 'water lightbow',
		description = 'Deals a light attack.',
		icon = '/images/game/spelltree/flecha',
	},
	["water heavybow"] = {
		spellId = 236,
		words = 'water heavybow',
		description = 'Deals a heavy attack.',
		icon = '/images/game/spelltree/flechas',
	},
	["water lightclub"] = {
		spellId = 237,
		words = 'water lightclub',
		description = 'Deals a light attack.',
		icon = '/images/game/spelltree/club',
	},
	["water heavyclub"] = {
		spellId = 238,
		words = 'water heavyclub',
		description = 'Deals a heavy attack.',
		icon = '/images/game/spelltree/clubs',
	},
	["water shieldbash"] = {
		spellId = 239,
		words = 'water shieldbash',
		description = 'Deals a heavy attack.',
		icon = '/images/game/spelltree/spell_03',
	},
	["water lightsword"] = {
		spellId = 240,
		words = 'water lightsword',
		description = 'Deals a light attack.',
		icon = '/images/game/spelltree/sword',
	},
	["water heavysword"] = {
		spellId = 241,
		words = 'water heavysword',
		description = 'Deals a heavy attack.',
		icon = '/images/game/spelltree/swords',
	},
		["fire lightaxe"] = {
		spellId = 133,
		words = 'fire lightaxe',
		description = 'Deals a light attack.',
		icon = '/images/game/spelltree/axe',
	},
	["fire heavyaxe"] = {
		spellId = 134,
		words = 'fire heavyaxe',
		description = 'Deals a heavy attack.',
		icon = '/images/game/spelltree/axes',
	},
	["fire lightbow"] = {
		spellId = 135,
		words = 'fire lightbow',
		description = 'Deals a light attack.',
		icon = '/images/game/spelltree/flecha',
	},
	["fire heavybow"] = {
		spellId = 136,
		words = 'fire heavybow',
		description = 'Deals a heavy attack.',
		icon = '/images/game/spelltree/flechas',
	},
	["fire lightclub"] = {
		spellId = 137,
		words = 'fire lightclub',
		description = 'Deals a light attack.',
		icon = '/images/game/spelltree/club',
	},
	["fire heavyclub"] = {
		spellId = 138,
		words = 'fire heavyclub',
		description = 'Deals a heavy attack.',
		icon = '/images/game/spelltree/clubs',
	},
	["fire shieldbash"] = {
		spellId = 139,
		words = 'fire shieldbash',
		description = 'Deals a heavy attack.',
		icon = '/images/game/spelltree/fire/fire_',
	},
	["fire lightsword"] = {
		spellId = 140,
		words = 'fire lightsword',
		description = 'Deals a light attack.',
		icon = '/images/game/spelltree/sword',
	},
	["fire heavysword"] = {
		spellId = 141,
		words = 'fire heavysword',
		description = 'Deals a heavy attack.',
		icon = '/images/game/spelltree/swords',
	},
}

SpellTree = {
	-- colar aqui a mesma tabela spelltree do servidor, irá poupar tempo e servirá como cache pro client
	[VOCATION_FIRE] = {
        [1] = {scroll_level = 1, scroll_type = "initial", scroll_count = 1, spells = {"fire whip", "fire recover"}},
		[2] = {scroll_level = 5, scroll_type = "bronze", scroll_count = 1, spells = {"fire recover", "fire urecover"}},
        [3] = {scroll_level = 8, scroll_type = "bronze", scroll_count = 1, spells = {"fire kick", "fire wave"}},
		[4] = {scroll_level = 12, scroll_type = "bronze", scroll_count = 1, spells = {"fire skyfall"}},
		[5] = {scroll_level = 16, scroll_type = "silver", scroll_count = 1, spells = {"fire jump", "fire blast"}},
		[6] = {scroll_level = 20, scroll_type = "silver", scroll_count = 1, spells = {"fire impulse"}},
		[7] = {scroll_level = 25, scroll_type = "silver", scroll_count = 1, spells = {"fire bolt"}},
		[8] = {scroll_level = 30, scroll_type = "silver", scroll_count = 1, spells = {"fire res"}},
		[9] = {scroll_level = 36, scroll_type = "gold", scroll_count = 1, spells = {"fire star"}},
		[10] = {scroll_level = 42, scroll_type = "gold", scroll_count = 1, spells = {"fire cannon"}},
		[11] = {scroll_level = 46, scroll_type = "gold", scroll_count = 1, spells = {"fire wrath"}},
		[12] = {scroll_level = 50, scroll_type = "gold", scroll_count = 1, spells = {"fire focus"}},
		[13] = {scroll_level = 55, scroll_type = "gold", scroll_count = 1, spells = {"fire lightning"}},
		[14] = {scroll_level = 60, scroll_type = "platinum", scroll_count = 1, spells = {"fire bomb"}},
		[15] = {scroll_level = 65, scroll_type = "platinum", scroll_count = 1, spells = {"fire clock"}},
		[16] = {scroll_level = 70, scroll_type = "platinum", scroll_count = 1, spells = {"fire thunderbolt"}},
		[17] = {scroll_level = 80, scroll_type = "platinum", scroll_count = 1, spells = {"fire meteor"}},
		[18] = {scroll_level = 90, scroll_type = "platinum", scroll_count = 1, spells = {"fire striker"}},
		[19] = {scroll_level = 100, scroll_type = "platinum", scroll_count = 1, spells = {"fire overload"}},
		[20] = {scroll_level = 110, scroll_type = "platinum", scroll_count = 1, spells = {"fire explosion"}},
		[21] = {scroll_level = 130, scroll_type = "platinum", scroll_count = 1, spells = {"fire voltage"}},
		[22] = {scroll_level = 150, scroll_type = "platinum", scroll_count = 1, spells = {"fire thunderstorm"}},
		[23] = {scroll_level = 200, scroll_type = "platinum", scroll_count = 1, spells = {"fire discharge"}},
		[24] = {scroll_level = 250, scroll_type = "platinum", scroll_count = 1, spells = {"fire conflagration"}}
	},
	[VOCATION_WATER] = {
        [1] = {scroll_level = 1, scroll_type = "initial", scroll_count = 1, spells = {"water whip"}},
		[2] = {scroll_level = 5, scroll_type = "bronze", scroll_count = 1, spells = {"water recover", "water urecover"}},
        [3] = {scroll_level = 8, scroll_type = "bronze", scroll_count = 1, spells = {"water explosion"}},
		[4] = {scroll_level = 12, scroll_type = "bronze", scroll_count = 1, spells = {"water heal", "water sheal"}},
		[5] = {scroll_level = 16, scroll_type = "silver", scroll_count = 1, spells = {"water jump", "water wave"}},
		[6] = {scroll_level = 20, scroll_type = "silver", scroll_count = 1, spells = {"water icespikes"}},
		[7] = {scroll_level = 25, scroll_type = "silver", scroll_count = 1, spells = {"water res"}},
		[8] = {scroll_level = 30, scroll_type = "silver", scroll_count = 1, spells = {"water shards"}},
		[9] = {scroll_level = 36, scroll_type = "gold", scroll_count = 1, spells = {"water surf"}},
		[10] = {scroll_level = 42, scroll_type = "gold", scroll_count = 1, spells = {"water cannon"}},
		[11] = {scroll_level = 46, scroll_type = "gold", scroll_count = 1, spells = {"water regen", "water sregen", "water mregen"}},
		[12] = {scroll_level = 50, scroll_type = "gold", scroll_count = 1, spells = {"water bloodcontrol"}},
		[13] = {scroll_level = 55, scroll_type = "gold", scroll_count = 1, spells = {"water punch"}},
		[14] = {scroll_level = 60, scroll_type = "platinum", scroll_count = 1, spells = {"water dragon"}},
		[15] = {scroll_level = 65, scroll_type = "platinum", scroll_count = 1, spells = {"water rain"}},
		[16] = {scroll_level = 70, scroll_type = "platinum", scroll_count = 1, spells = {"water bubbles"}},
		[17] = {scroll_level = 80, scroll_type = "platinum", scroll_count = 1, spells = {"water protect"}},
		[18] = {scroll_level = 90, scroll_type = "platinum", scroll_count = 1, spells = {"water icebolt"}},
		[19] = {scroll_level = 100, scroll_type = "platinum", scroll_count = 1, spells = {"water flow"}},
		[20] = {scroll_level = 110, scroll_type = "platinum", scroll_count = 1, spells = {"water water icegolem"}},
		[21] = {scroll_level = 130, scroll_type = "platinum", scroll_count = 1, spells = {"water tsunami"}},
		[22] = {scroll_level = 150, scroll_type = "platinum", scroll_count = 1, spells = {"water clock"}},
		[23] = {scroll_level = 200, scroll_type = "platinum", scroll_count = 1, spells = {"water blizzard"}},
		[24] = {scroll_level = 250, scroll_type = "platinum", scroll_count = 1, spells = {"water bloodbending"}}
	},
	[VOCATION_AIR] = {
        [1] = {scroll_level = 1, scroll_type = "initial", scroll_count = 1, spells = {"air burst", "air ball"}},
		[2] = {scroll_level = 5, scroll_type = "bronze", scroll_count = 1, spells = {"air recover", "air urecover"}},
        [3] = {scroll_level = 8, scroll_type = "bronze", scroll_count = 1, spells = {"air burst"}},
		[4] = {scroll_level = 12, scroll_type = "bronze", scroll_count = 1, spells = {"air run"}},
		[5] = {scroll_level = 16, scroll_type = "silver", scroll_count = 1, spells = {"air jump"}},
		[6] = {scroll_level = 20, scroll_type = "silver", scroll_count = 1, spells = {"air force"}},
		[7] = {scroll_level = 25, scroll_type = "silver", scroll_count = 1, spells = {"air gust"}},
		[8] = {scroll_level = 30, scroll_type = "gold", scroll_count = 1, spells = {"air gale", "air icywind"}},
		[9] = {scroll_level = 36, scroll_type = "gold", scroll_count = 1, spells = {"air boost"}},
		[10] = {scroll_level = 42, scroll_type = "gold", scroll_count = 1, spells = {"air fan"}},
		[11] = {scroll_level = 46, scroll_type = "platinum", scroll_count = 1, spells = {"air wings"}},
		[12] = {scroll_level = 50, scroll_type = "platinum", scroll_count = 1, spells = {"air suffocation", "air jail"}},
		[13] = {scroll_level = 55, scroll_type = "platinum", scroll_count = 1, spells = {"air hurricane"}},
		[14] = {scroll_level = 60, scroll_type = "platinum", scroll_count = 1, spells = {"air tempest"}},
		[15] = {scroll_level = 65, scroll_type = "platinum", scroll_count = 1, spells = {"air windblast"}},
		[16] = {scroll_level = 70, scroll_type = "platinum", scroll_count = 1, spells = {"air tornado"}},
		[17] = {scroll_level = 80, scroll_type = "platinum", scroll_count = 1, spells = {"air barrier"}},
		[18] = {scroll_level = 90, scroll_type = "platinum", scroll_count = 1, spells = {"air trap"}},
		[19] = {scroll_level = 100, scroll_type = "platinum", scroll_count = 1, spells = {"air doom"}},
		[20] = {scroll_level = 110, scroll_type = "platinum", scroll_count = 1, spells = {"air bomb"}},
		[21] = {scroll_level = 130, scroll_type = "platinum", scroll_count = 1, spells = {"air windstorm"}},
		[22] = {scroll_level = 150, scroll_type = "platinum", scroll_count = 1, spells = {"air stormcall"}},
		[23] = {scroll_level = 200, scroll_type = "platinum", scroll_count = 1, spells = {"air vortex"}},
		[24] = {scroll_level = 250, scroll_type = "platinum", scroll_count = 1, spells = {"air deflection"}}
	},
	[VOCATION_EARTH] = {
        [1] = {scroll_level = 1, scroll_type = "initial", scroll_count = 1, spells = {"earth whip", "earth crush"}},
		[2] = {scroll_level = 5, scroll_type = "bronze", scroll_count = 1, spells = {"earth recover", "earth urecover"}},
        [3] = {scroll_level = 8, scroll_type = "bronze", scroll_count = 1, spells = {"earth punch"}},
		[4] = {scroll_level = 12, scroll_type = "bronze", scroll_count = 1, spells = {"earth rock"}},
		[5] = {scroll_level = 16, scroll_type = "silver", scroll_count = 1, spells = {"earth jump"}},
		[6] = {scroll_level = 20, scroll_type = "silver", scroll_count = 1, spells = {"earth pull"}},
		[7] = {scroll_level = 25, scroll_type = "silver", scroll_count = 1, spells = {"earth growth"}},
		[8] = {scroll_level = 30, scroll_type = "silver", scroll_count = 1, spells = {"earth collapse"}},
		[9] = {scroll_level = 36, scroll_type = "gold", scroll_count = 1, spells = {"earth track"}},
		[10] = {scroll_level = 42, scroll_type = "gold", scroll_count = 1, spells = {"earth petrify"}},
		[11] = {scroll_level = 46, scroll_type = "gold", scroll_count = 1, spells = {"earth fury"}},
		[12] = {scroll_level = 50, scroll_type = "gold", scroll_count = 1, spells = {"earth control"}},
		[13] = {scroll_level = 55, scroll_type = "gold", scroll_count = 1, spells = {"earth leech"}},
		[14] = {scroll_level = 60, scroll_type = "platinum", scroll_count = 1, spells = {"earth smash"}},
		[15] = {scroll_level = 65, scroll_type = "platinum", scroll_count = 1, spells = {"earth ingrain"}},
		[16] = {scroll_level = 70, scroll_type = "platinum", scroll_count = 1, spells = {"earth fists"}},
		[17] = {scroll_level = 80, scroll_type = "platinum", scroll_count = 1, spells = {"earth arena"}},
		[18] = {scroll_level = 90, scroll_type = "platinum", scroll_count = 1, spells = {"earth curse"}},
		[19] = {scroll_level = 100, scroll_type = "platinum", scroll_count = 1, spells = {"earth quake"}},
		[20] = {scroll_level = 110, scroll_type = "platinum", scroll_count = 1, spells = {"earth cataclysm"}},
		[21] = {scroll_level = 130, scroll_type = "platinum", scroll_count = 1, spells = {"earth aura"}},
		[22] = {scroll_level = 150, scroll_type = "platinum", scroll_count = 1, spells = {"earth armor"}},
		[23] = {scroll_level = 200, scroll_type = "platinum", scroll_count = 1, spells = {"earth lavaball"}},
		[24] = {scroll_level = 250, scroll_type = "platinum", scroll_count = 1, spells = {"earth metalwall"}}
	}
}